namespace Concurrent_forms
{
    partial class Level2
    {
        public System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        public void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Level2));
            this.pictureBox9 = new System.Windows.Forms.PictureBox();
            this.pictureBox8 = new System.Windows.Forms.PictureBox();
            this.pictureBox7 = new System.Windows.Forms.PictureBox();
            this.pictureBox5 = new System.Windows.Forms.PictureBox();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.slot3 = new System.Windows.Forms.PictureBox();
            this.slot2 = new System.Windows.Forms.PictureBox();
            this.slot1 = new System.Windows.Forms.PictureBox();
            this.toolbox = new System.Windows.Forms.PictureBox();
            this.infobox = new System.Windows.Forms.PictureBox();
            this.description = new System.Windows.Forms.PictureBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.infobox_img = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.richTextBox1 = new System.Windows.Forms.RichTextBox();
            this.nextlvl = new System.Windows.Forms.PictureBox();
            this.victory = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.slot3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.slot2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.slot1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.toolbox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infobox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.description)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.infobox_img)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nextlvl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.victory)).BeginInit();
            this.SuspendLayout();
            this.pictureBox9.Image = global::Concurrent_forms.Properties.Resources.inductor;
            this.pictureBox9.Location = new System.Drawing.Point(55, 601);
            this.pictureBox9.Name = "pictureBox9";
            this.pictureBox9.Size = new System.Drawing.Size(62, 96);
            this.pictureBox9.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox9.TabIndex = 8;
            this.pictureBox9.TabStop = false;
            this.pictureBox9.Tag = "inductor_tag";
            this.pictureBox9.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pictureBox9_MouseDown);
            this.pictureBox8.Image = global::Concurrent_forms.Properties.Resources.capacitor;
            this.pictureBox8.Location = new System.Drawing.Point(226, 601);
            this.pictureBox8.Name = "pictureBox8";
            this.pictureBox8.Size = new System.Drawing.Size(62, 96);
            this.pictureBox8.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox8.TabIndex = 7;
            this.pictureBox8.TabStop = false;
            this.pictureBox8.Tag = "capacitor_tag";
            this.pictureBox8.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pictureBox8_MouseDown);
            this.pictureBox7.Image = global::Concurrent_forms.Properties.Resources.resistor;
            this.pictureBox7.Location = new System.Drawing.Point(136, 601);
            this.pictureBox7.Name = "pictureBox7";
            this.pictureBox7.Size = new System.Drawing.Size(66, 96);
            this.pictureBox7.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox7.TabIndex = 6;
            this.pictureBox7.TabStop = false;
            this.pictureBox7.Tag = "resistor_tag";
            this.pictureBox7.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pictureBox7_MouseDown);
            this.pictureBox5.Image = global::Concurrent_forms.Properties.Resources.check_default;
            this.pictureBox5.Location = new System.Drawing.Point(97, 26);
            this.pictureBox5.Name = "pictureBox5";
            this.pictureBox5.Size = new System.Drawing.Size(239, 84);
            this.pictureBox5.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox5.TabIndex = 4;
            this.pictureBox5.TabStop = false;
            this.pictureBox5.Click += new System.EventHandler(this.pictureBox5_Click);
            this.pictureBox5.MouseLeave += new System.EventHandler(this.pictureBox5_MouseLeave);
            this.pictureBox5.MouseHover += new System.EventHandler(this.pictureBox5_MouseHover);
            this.pictureBox4.Image = global::Concurrent_forms.Properties.Resources.left_arr_default;
            this.pictureBox4.Location = new System.Drawing.Point(12, 26);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(89, 84);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox4.TabIndex = 3;
            this.pictureBox4.TabStop = false;
            this.pictureBox4.Click += new System.EventHandler(this.pictureBox4_Click);
            this.pictureBox4.MouseEnter += new System.EventHandler(this.pictureBox4_MouseEnter);
            this.pictureBox4.MouseLeave += new System.EventHandler(this.pictureBox4_MouseLeave);
            this.slot3.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.slot3.Location = new System.Drawing.Point(368, 284);
            this.slot3.Name = "slot3";
            this.slot3.Size = new System.Drawing.Size(73, 98);
            this.slot3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.slot3.TabIndex = 2;
            this.slot3.TabStop = false;
            this.slot3.DragDrop += new System.Windows.Forms.DragEventHandler(this.slot3_DragDrop);
            this.slot3.DragEnter += new System.Windows.Forms.DragEventHandler(this.slot3_DragEnter);
            this.slot2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.slot2.Location = new System.Drawing.Point(506, 284);
            this.slot2.Name = "slot2";
            this.slot2.Size = new System.Drawing.Size(67, 98);
            this.slot2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.slot2.TabIndex = 1;
            this.slot2.TabStop = false;
            this.slot2.DragDrop += new System.Windows.Forms.DragEventHandler(this.slot2_DragDrop);
            this.slot2.DragEnter += new System.Windows.Forms.DragEventHandler(this.slot2_DragEnter);
            this.slot1.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.slot1.Location = new System.Drawing.Point(236, 284);
            this.slot1.Name = "slot1";
            this.slot1.Size = new System.Drawing.Size(72, 98);
            this.slot1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.slot1.TabIndex = 0;
            this.slot1.TabStop = false;
            this.slot1.DragDrop += new System.Windows.Forms.DragEventHandler(this.slot1_DragDrop);
            this.slot1.DragEnter += new System.Windows.Forms.DragEventHandler(this.slot1_DragEnter);
            this.toolbox.Image = global::Concurrent_forms.Properties.Resources.toolbox;
            this.toolbox.Location = new System.Drawing.Point(25, 591);
            this.toolbox.Name = "toolbox";
            this.toolbox.Size = new System.Drawing.Size(453, 116);
            this.toolbox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.toolbox.TabIndex = 9;
            this.toolbox.TabStop = false;
            this.infobox.Image = global::Concurrent_forms.Properties.Resources.infobox;
            this.infobox.Location = new System.Drawing.Point(766, 4);
            this.infobox.Name = "infobox";
            this.infobox.Size = new System.Drawing.Size(230, 221);
            this.infobox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.infobox.TabIndex = 10;
            this.infobox.TabStop = false;
            this.description.Image = global::Concurrent_forms.Properties.Resources.description;
            this.description.Location = new System.Drawing.Point(785, 231);
            this.description.Name = "description";
            this.description.Size = new System.Drawing.Size(199, 476);
            this.description.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.description.TabIndex = 11;
            this.description.TabStop = false;
            this.pictureBox1.Image = global::Concurrent_forms.Properties.Resources.biglogo;
            this.pictureBox1.Location = new System.Drawing.Point(368, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(358, 107);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 12;
            this.pictureBox1.TabStop = false;
            this.infobox_img.Image = global::Concurrent_forms.Properties.Resources.information;
            this.infobox_img.Location = new System.Drawing.Point(814, 53);
            this.infobox_img.Name = "infobox_img";
            this.infobox_img.Size = new System.Drawing.Size(134, 128);
            this.infobox_img.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.infobox_img.TabIndex = 13;
            this.infobox_img.TabStop = false;
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(41, 162);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(685, 340);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox3.TabIndex = 15;
            this.pictureBox3.TabStop = false;
            this.pictureBox2.Image = global::Concurrent_forms.Properties.Resources.help_default;
            this.pictureBox2.Location = new System.Drawing.Point(495, 591);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(113, 112);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox2.TabIndex = 17;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            this.pictureBox2.MouseEnter += new System.EventHandler(this.pictureBox2_MouseEnter);
            this.pictureBox2.MouseLeave += new System.EventHandler(this.pictureBox2_MouseLeave);
            this.richTextBox1.BackColor = System.Drawing.Color.White;
            this.richTextBox1.Font = new System.Drawing.Font("Calibri", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.richTextBox1.Location = new System.Drawing.Point(804, 251);
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.ReadOnly = true;
            this.richTextBox1.Size = new System.Drawing.Size(165, 434);
            this.richTextBox1.TabIndex = 18;
            this.richTextBox1.Text = resources.GetString("richTextBox1.Text");
            this.nextlvl.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.nextlvl.Image = global::Concurrent_forms.Properties.Resources.dalej_default;
            this.nextlvl.Location = new System.Drawing.Point(614, 591);
            this.nextlvl.Name = "nextlvl";
            this.nextlvl.Size = new System.Drawing.Size(112, 112);
            this.nextlvl.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.nextlvl.TabIndex = 19;
            this.nextlvl.TabStop = false;
            this.nextlvl.Click += new System.EventHandler(this.nextlvl_Click);
            this.nextlvl.MouseEnter += new System.EventHandler(this.nextlvl_MouseEnter);
            this.nextlvl.MouseLeave += new System.EventHandler(this.nextlvl_MouseLeave);
            this.victory.Image = global::Concurrent_forms.Properties.Resources.gif2;
            this.victory.Location = new System.Drawing.Point(12, 125);
            this.victory.Name = "victory";
            this.victory.Size = new System.Drawing.Size(748, 457);
            this.victory.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.victory.TabIndex = 20;
            this.victory.TabStop = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::Concurrent_forms.Properties.Resources.bgcolor;
            this.ClientSize = new System.Drawing.Size(1008, 715);
            this.Controls.Add(this.victory);
            this.Controls.Add(this.nextlvl);
            this.Controls.Add(this.richTextBox1);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.infobox_img);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.pictureBox9);
            this.Controls.Add(this.pictureBox8);
            this.Controls.Add(this.pictureBox7);
            this.Controls.Add(this.pictureBox5);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.slot3);
            this.Controls.Add(this.slot2);
            this.Controls.Add(this.slot1);
            this.Controls.Add(this.toolbox);
            this.Controls.Add(this.description);
            this.Controls.Add(this.infobox);
            this.Controls.Add(this.pictureBox3);
            this.Name = "Level2";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Level2";
            this.Load += new System.EventHandler(this.Level2_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.slot3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.slot2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.slot1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.toolbox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infobox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.description)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.infobox_img)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nextlvl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.victory)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.PictureBox slot1;
        public System.Windows.Forms.PictureBox slot2;
        public System.Windows.Forms.PictureBox slot3;
        public System.Windows.Forms.PictureBox pictureBox4;
        public System.Windows.Forms.PictureBox pictureBox5;
        public System.Windows.Forms.PictureBox pictureBox7;
        public System.Windows.Forms.PictureBox pictureBox8;
        public System.Windows.Forms.PictureBox pictureBox9;
        public System.Windows.Forms.PictureBox toolbox;
        public System.Windows.Forms.PictureBox infobox;
        public System.Windows.Forms.PictureBox description;
        public System.Windows.Forms.PictureBox pictureBox1;
        public System.Windows.Forms.PictureBox infobox_img;
        public System.Windows.Forms.PictureBox pictureBox3;
        public System.Windows.Forms.PictureBox pictureBox2;
        public System.Windows.Forms.RichTextBox richTextBox1;
        public System.Windows.Forms.PictureBox nextlvl;
        public System.Windows.Forms.PictureBox victory;
    }
}